// Generated by CoffeeScript 1.10.0

/*
 * Request XHR
 */

(function() {
  $W.Ajax = (function() {
    return {
      request: function(obj) {
        var bodyXhr, method, obj_loading, parametros, value, xhr;
        parametros = '';
        if (typeof obj.id_ventana === 'undefined') {
          console.warn("Debe enviar el parametro id_ventana, para poder mostrar el loading");
          return;
        }
        if (typeof obj.params !== 'undefined') {
          for (value in obj.params) {
            parametros += parametros === '' ? value + "=" + obj.params[value] : "&" + value + "=" + obj.params[value];
          }
        }
        if (obj.modal === true || obj.modal === '') {
          obj_loading = {
            id_ventana: obj.id_ventana,
            text: obj.text,
            loader: obj.loader,
            icono: obj.iconFinish,
            icono: obj.iconFinish,
            texto: obj.textFinish,
            duracion: obj.duracionFinish,
            estado: 'on'
          };
          Win.loading(obj_loading);
        }
        xhr = new XMLHttpRequest;
        bodyXhr = obj.url + '?' + parametros;
        method = obj.method || 'POST';
        xhr.open(method, bodyXhr, true);
        xhr.onreadystatechange = function() {
          var response;
          if (xhr.readyState === 4) {
            response = xhr.responseText;
            if ((obj.modal === true || obj.modal === '') && (obj.autoClose === true || obj.autoClose === '')) {
              obj_loading.estado = 'off';
              Win.loading(obj_loading);
            }
            return obj.success(response, xhr);
          } else {
            if ((obj.modal === true || obj.modal === '') && (obj.autoClose === true || obj.autoClose === '')) {
              obj_loading.estado = 'off';
              Win.loading(obj_loading);
            }
            return obj.failure(xhr);
          }
        };
        return xhr.send(null);
      },
      load: function(objDom, obj) {
        var bodyXhr, divLoad, method, panel, parametros, text, value, xhr;
        parametros = '';
        panel = objDom;
        if (typeof obj.params !== 'undefined') {
          for (value in obj.params) {
            parametros += parametros === '' ? value + "=" + obj.params[value] : "&" + value + "=" + obj.params[value];
          }
        }
        text = obj.text || 'cargando...';
        divLoad = document.createElement('div');
        divLoad.className = "win-content-min-load";
        divLoad.innerHTML = "<div class=\"win-content-min-load-img\"> <div class=\"win-min-load-ajax\"></div> </div> <div class=\"win-content-min-load-label\">" + text + "</div>";
        objDom.appendChild(divLoad);
        xhr = new XMLHttpRequest;
        bodyXhr = obj.url + '?' + parametros;
        method = obj.method || 'POST';
        xhr.open(method, bodyXhr, true);
        xhr.onreadystatechange = function() {
          console.log(panel);
          panel.style.backgroundColor = "red";
          return panel.innerHTML = 222;
        };
        return xhr.send(null);
      }
    };
  })();

}).call(this);
