// Generated by CoffeeScript 1.10.0

/*
 * Win.js
 * @namespeace Win
 *
 * @version 0.1
 * @author Jhon Marroquin || @jhon3rick
 * @author Jonatan Herran || @jonatan2874
 *
 */

(function() {
  "use strict";
  (function($W) {
    var CONTBODY, CONTPANEL, IDGLOBAL, _button, _router, _tbar;
    IDGLOBAL = '';
    CONTPANEL = 0;
    CONTBODY = 0;
    $W.Window = function(obj) {
      var autoDestroy, autoLoad, autoScroll, bgBody, bgTitle, body, bodyColor, bodyStyle, clsBody, divClose, drag, height, html, id, left, modal, section, theme, title, titleStyle, top, width, win, winModal;
      width = obj.width || 300;
      height = obj.height || 300;
      id = obj.id || '';
      title = obj.title || '';
      titleStyle = obj.titleStyle || '';
      modal = obj.modal || '';
      autoScroll = obj.autoScroll || '';
      autoDestroy = obj.autoDestroy || '';
      autoLoad = obj.autoLoad || '';
      html = obj.html || '';
      drag = obj.drag || '';
      theme = obj.theme || '';
      bodyStyle = obj.bodyStyle || '';
      bodyColor = obj.bodyColor || '#FFF';
      body = $W('body')[0];
      win = this;
      clsBody = typeof obj.type !== 'undefined' && obj.type !== '' ? 'alert' : '';
      winModal = document.createElement('div');
      IDGLOBAL = id;
      bgBody = obj.bgBody ? 'background-color:' + obj.bgBody + ';' : '';
      bgTitle = obj.bgTitle ? 'background-color:' + obj.bgTitle + ';' : '';
      divClose = obj.closable !== false ? "<div class=\"win-title-btn\" id=\"btn_close_ventana_" + id + "\" onclick=\"" + id + ".close()\"></div>" : "";
      left = body.offsetWidth < width ? 0 : (body.offsetWidth - width) / 2;
      top = body.offsetHeight < height ? 0 : (body.offsetHeight - height) / 2;
      winModal.setAttribute("id", "win-modal-" + id);
      winModal.setAttribute("class", "win-modal");
      winModal.innerHTML += "<div style=\"width:" + width + "; height:" + height + "; top:" + top + "; left:" + left + "; " + bgBody + " " + bodyStyle + "\" id=\"" + id + "\" class=\"win-marco\"> <div class=\"win-file-resize\" data-resize=\"top\" id=\"win-resize-top-" + id + "\"></div> <div class=\"win-file-resize\" data-resize=\"bottom\" id=\"win-resize-bottom-" + id + "\"></div> <div class=\"win-file-resize\" data-resize=\"left\" id=\"win-resize-left-" + id + "\"></div> <div class=\"win-file-resize\" data-resize=\"right\" id=\"win-resize-right-" + id + "\"></div> <div class=\"win-modal-parent\" id=\"win-modal-window_" + id + "\"> <div class=\"win-modal-content\"> <div class=\"win-loader-default\" id=\"win-loader-" + id + "\"></div> <div class=\"win-modal-label\" id=\"label-load-" + id + "\"></div> </div> </div> <header> <div class=\"win-title\" id=\"win-title-" + id + "\" style=\"" + bgTitle + " " + titleStyle + "\"> <div class=\"win-title-txt\">" + title + "</div> " + divClose + " </div> </header> <section id=\"win-window-section-" + id + "\"></section> </div>";
      body.appendChild(winModal);
      section = document.getElementById("win-window-section-" + id);
      if (typeof obj.items !== 'undefined') {
        _router(obj.items, section);
      }
      if (typeof obj.autoLoad !== 'undefined') {
        _body(obj, section);
      }
      return {
        close: function() {
          return $W("\#win-modal-" + id)[0].parentNode.removeChild($W("\#win-modal-" + id)[0]);
        }
      };
    };
    $W.tbar = function(obj) {
      var parent;
      IDGLOBAL = obj.idApply;
      parent = document.getElementById("" + obj.idApply);
      parent.className = "win-tbar";
      return _router(obj.items, parent);
    };
    $W.get = function(element_id) {
      return {
        load: function(obj) {
          var dom_element;
          dom_element = $W(element_id)[0];
          return $W.Ajax.load(dom_element, obj);
        },
        element: function() {
          return $W(element_id);
        }
      };
    };

    /*
    	@method _router
    	@param  arr child
    	@param  obj ObjetoDom parent
     */
    _router = function(obj, parent) {
      var float;
      if (typeof obj === 'object') {
        float = 'left';
        obj.forEach(function(json, index, element) {
          switch (json.xtype) {
            case 'button':
              return _button(json, parent);
            case 'tbar':
              return _tbar(json, parent);
          }
        });
        if (float === 'left') {
          return parent.innerHTML += '<div></div>';
        }
      }
    };

    /*
    	@method _button
    	@param  obj objectDom parent and config
     */
    _button = function(obj, parent) {
      var boton, cls, id, text, width;
      text = obj.text || '';
      id = obj.id || '';
      cls = obj.cls || '';
      width = obj.width || 50;
      boton = document.createElement('div');
      boton.setAttribute("id", id);
      boton.setAttribute("class", "win-btn");
      if (obj.width > 0) {
        boton.setAttribute("style", "width: " + obj.width + "px;");
      }
      boton.innerHTML = "<button class=\"" + cls + "\">" + text + "</button>";
      parent.appendChild(boton);
      document.getElementById(boton.id).onclhgick = alert(3);
      return true;
    };

    /*
    	@method _tbar
    	@param  obj objectDom parent and config
     */
    return _tbar = function(obj, parent) {
      var id, items, tbar;
      id = obj.id || parent.id || '';
      items = obj.items || '';
      parent.innerHTML += "<div class=\"win-tbar\" id=\"win-tbar-" + id + "\"></div>";
      tbar = document.getElementById("win-tbar-" + id);
      return _router(obj.items, tbar);
    };
  })(Win);

}).call(this);
