// Generated by CoffeeScript 1.10.0

/*
 * Request XHR
 */

(function() {
  $W.Ajax = (function() {
    return {
      request: function(obj) {
        var bodyXhr, method, obj_loading, param, value, xhr;
        param = '';
        if (typeof obj.id_ventana === 'undefined') {
          console.warn("Debe enviar el parametro id_ventana, para poder mostrar el loading");
          return;
        }
        if (typeof obj.params !== 'undefined') {
          for (value in obj.params) {
            param += param === '' ? value + "=" + obj.params[value] : "&" + value + "=" + obj.params[value];
          }
        }
        if (obj.modal === true || obj.modal === '') {
          obj_loading = {
            id_ventana: obj.id_ventana,
            text: obj.text,
            loader: obj.loader,
            icono: obj.iconFinish,
            icono: obj.iconFinish,
            texto: obj.textFinish,
            duracion: obj.duracionFinish,
            estado: 'on'
          };
          Win.loading(obj_loading);
        }
        xhr = new XMLHttpRequest;
        bodyXhr = obj.url + '?' + param;
        method = obj.method || 'POST';
        xhr.open(method, bodyXhr, true);
        xhr.onreadystatechange = function() {
          var response;
          if (xhr.readyState === 4) {
            response = xhr.responseText;
            if ((obj.modal === true || obj.modal === '') && (obj.autoClose === true || obj.autoClose === '')) {
              obj_loading.estado = 'off';
              Win.loading(obj_loading);
            }
            return obj.success(response, xhr);
          } else {
            if ((obj.modal === true || obj.modal === '') && (obj.autoClose === true || obj.autoClose === '')) {
              obj_loading.estado = 'off';
              Win.loading(obj_loading);
            }
            return obj.failure(xhr);
          }
        };
        return xhr.send(null);
      },
      load: function(parent, obj) {
        var bodyXhr, method, param, text, value, xhr;
        param = '';
        if (typeof obj.params !== 'undefined') {
          for (value in obj.params) {
            param += param === '' ? value + "=" + obj.params[value] : "&" + value + "=" + obj.params[value];
          }
        }
        text = obj.text || 'cargando...';
        parent.innerHTML = "<div class=\"win-content-min-load\" > <div class=\"win-content-min-load-img\"> <div class=\"win-min-load-ajax\"></div> </div> <div class=\"win-content-min-load-label\">" + text + "</div> </div>";
        xhr = new XMLHttpRequest;
        bodyXhr = obj.url + '?' + param;
        method = obj.method || 'POST';
        xhr.open(method, bodyXhr, true);
        xhr.onreadystatechange = function() {
          var i, j, len, load, results, script, tagScript;
          if (xhr.readyState === 4) {
            load = document.getElementById(parent.id);
            load.innerHTML = xhr.responseText;
            script = load.getElementsByTagName('script');
            results = [];
            for (j = 0, len = script.length; j < len; j++) {
              i = script[j];
              tagScript = document.createElement('script');
              i.parentNode.replaceChild(tagScript, i);
              results.push(tagScript.innerHTML = i.innerHTML);
            }
            return results;
          }
        };
        return xhr.send(null);
      }
    };
  })();

}).call(this);
